//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HumanarizeClockTime.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RemarkResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RemarkResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HumanarizeClockTime.Resource.RemarkResource", typeof(RemarkResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input a valid time in 24hrs (HH:mm) format to view its verbose equivalent, or simply press enter to view the current time..
        /// </summary>
        internal static string DisplayInputDescription {
            get {
                return ResourceManager.GetString("DisplayInputDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;quit&apos; or &apos;q&apos; to exit, or &apos;help&apos; or &apos;h&apos; for more details..
        /// </summary>
        internal static string ExitSuggestion {
            get {
                return ResourceManager.GetString("ExitSuggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display server time program. Hit the &apos;Enter&apos; key to view the current time. Type time in 24HRS (HH:mm) format to view its verbose equivalent. To exit type &apos;quit&apos; or &apos;q&apos;.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours can not be greater that 24.
        /// </summary>
        internal static string HoursGreaterThan23 {
            get {
                return ResourceManager.GetString("HoursGreaterThan23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter time in HH:mm (HH&gt;=0 or &lt;24 and MM&gt;=0 or &lt; 60) format or simply press enter to view the current time.
        /// </summary>
        internal static string IncorrectInputMessage {
            get {
                return ResourceManager.GetString("IncorrectInputMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter correct clock time.
        /// </summary>
        internal static string InvalidInput {
            get {
                return ResourceManager.GetString("InvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes can not be greater than 59.
        /// </summary>
        internal static string MinutesGreaterThan59 {
            get {
                return ResourceManager.GetString("MinutesGreaterThan59", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negative value is not allowed.
        /// </summary>
        internal static string NegativeValue {
            get {
                return ResourceManager.GetString("NegativeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for using Server Time program. Have a nice day..
        /// </summary>
        internal static string Thanks {
            get {
                return ResourceManager.GetString("Thanks", resourceCulture);
            }
        }
    }
}
